name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Run this only when code is pushed to 'main'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Download your code to the runner
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Log in to Docker Hub (Using the secrets you just set)
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build the image and Push it
      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mlops-app:latest
